site_name: Muath's Notes
site_url: https://example.com/

nav:
  - Home: index.md
  - 'Azure':
    - 'Azure VMs': azure-vm.md
  - 'AWS':
    - 'Glue': aws-glue.md
    - 'Date Pipeline': aws-data-pipeline.md
  - 'App Security':
    - 'OAuth2': oauth2.md
  - Streams: streams.md
  - 'Angular':
    - 'Learning Angular': angular/learning-angular.md
    - 'Angular Material': angular/angular-material.md
  - Docker: docker.md
  - Mac OS: mac-os.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

