site_name: Muath's Notes
site_url: https://example.com/

nav:
  - Home: index.md
  - Architecture:
    - 'Introduction': architecture/index.md
    - 'Streaming': architecture/streams.md
    - 'State Stores': architecture/state-stores.md
    - 'Initial Load': architecture/init-load.md
  - 'Programming':
    - 'Learning Angular': programming/learning-angular.md
    - 'Angular Material': programming/angular-material.md
  - 'AWS':
    - 'Private Link': aws/private-link.md
    - 'Glue': aws/aws-glue.md
    - 'Date Pipeline': aws/aws-data-pipeline.md
  - 'Azure':
    - 'General': azure/general.md
    - 'Azure VMs': azure/azure-vm.md
  - 'Tools':
    - 'Commands': tools/commands.md
    - 'Docker': tools/docker.md
    - 'Avro': tools/avro.md
    - 'Mac OS': tools/mac-os.md
  - 'Photography':
    - 'Final Cut Pro': light/fcp.md
    - 'FCP Shortcuts': light/fcp-shortcuts.md
    - 'Stunning Digital Photography': light/sdp.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

