site_name: Muath's Notes
site_url: https://example.com/

nav:
  - Home: index.md
  - 'Programming':
    - 'Learning Angular': programming/learning-angular.md
    - 'Angular Material': programming/angular-material.md
    - 'C#': programming/csharp.md
  - 'AWS':
    - 'Glue': aws/aws-glue.md
    - 'Date Pipeline': aws/aws-data-pipeline.md
  - 'Azure':
    - 'General': azure/general.md
    - 'Azure VMs': azure/azure-vm.md
  - 'Photography':
    - 'Final Cut Pro': photography/fcp.md
    - 'Stunning Digital Photography': photography/sdp.md
  - Docker: docker.md
  - Mac OS: mac-os.md
  - Streams: streams.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

